using System.Text;
using System.Text.RegularExpressions;

namespace NetForward.Converters.Startup;

/// <summary>
/// Converts a Global.asax.cs to a Program.cs scaffold for ASP.NET Core.
///
/// Fix: Previous regex required non-empty method body ([^}]*) which excluded
/// empty handlers like `protected void Application_BeginRequest() { }`.
/// New approach: detect handler NAMES first (presence check), then extract
/// body separately. This correctly handles empty, single-line, and multi-line bodies.
/// </summary>
public sealed class GlobalAsaxConverter
{
    public sealed record ConversionResult(
        string OutputPath,
        string ProgramCsContent,
        IReadOnlyList<string> Notes);

    // Detects the presence of a named handler — body may be empty.
    private static readonly Regex HandlerPresenceRegex = new(
        @"(?:protected|public)\s+(?:override\s+)?void\s+(?<name>Application_\w+|Session_\w+)\s*\([^)]*\)",
        RegexOptions.Compiled | RegexOptions.Singleline);

    // Extracts the body between braces for a named handler (handles empty bodies too).
    private static readonly Regex HandlerBodyRegex = new(
        @"(?:protected|public)\s+(?:override\s+)?void\s+(?<name>Application_\w+|Session_\w+)\s*\([^)]*\)\s*\{(?<body>[^{}]*)\}",
        RegexOptions.Compiled | RegexOptions.Singleline);

    public ConversionResult Convert(string globalAsaxCsPath, string outputDirectory)
    {
        if (!File.Exists(globalAsaxCsPath))
            throw new FileNotFoundException(
                $"Global.asax.cs not found: {globalAsaxCsPath}", globalAsaxCsPath);

        var source = File.ReadAllText(globalAsaxCsPath);
        var notes = new List<string>();

        // Detect which handlers are PRESENT (even if empty).
        var presentHandlers = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match m in HandlerPresenceRegex.Matches(source))
        {
            presentHandlers.Add(m.Groups["name"].Value);
        }

        // Extract bodies where non-empty.
        var handlerBodies = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (Match m in HandlerBodyRegex.Matches(source))
        {
            var name = m.Groups["name"].Value;
            var body = m.Groups["body"].Value.Trim();
            if (!string.IsNullOrWhiteSpace(body))
            {
                handlerBodies[name] = body;
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Program.cs — generated by NetForward from Global.asax.cs");
        sb.AppendLine("// Review all TODO comments before using in production.");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine();
        sb.AppendLine("var builder = WebApplication.CreateBuilder(args);");
        sb.AppendLine();
        sb.AppendLine("// TODO: Add services from your DI registrations");
        sb.AppendLine("builder.Services.AddControllersWithViews();");
        sb.AppendLine();

        // Session_Start → services registration hint (add before Build())
        if (presentHandlers.Contains("Session_Start"))
        {
            sb.AppendLine("// TODO: Session_Start was present. Add session configuration:");
            sb.AppendLine("// builder.Services.AddSession(options =>");
            sb.AppendLine("// {");
            sb.AppendLine("//     options.IdleTimeout = TimeSpan.FromMinutes(20);");
            sb.AppendLine("//     options.Cookie.HttpOnly = true;");
            sb.AppendLine("// });");
            sb.AppendLine();
            notes.Add("Session_Start detected. Add builder.Services.AddSession() and app.UseSession().");
        }

        // Application_Start body
        if (handlerBodies.TryGetValue("Application_Start", out var startBody))
        {
            sb.AppendLine("// Migrated from Application_Start:");
            foreach (var line in startBody.Split('\n').Select(l => l.TrimEnd()))
            {
                if (!string.IsNullOrWhiteSpace(line))
                    sb.AppendLine($"// {line}");
            }
            sb.AppendLine("// TODO: Move above code into appropriate builder.Services.Add* calls.");
            sb.AppendLine();
            notes.Add("Application_Start body preserved as comments. Move into builder.Services configuration.");
        }
        else if (presentHandlers.Contains("Application_Start"))
        {
            sb.AppendLine("// TODO: Application_Start was present but had an empty body.");
            sb.AppendLine();
        }

        sb.AppendLine("var app = builder.Build();");
        sb.AppendLine();
        sb.AppendLine("if (!app.Environment.IsDevelopment())");
        sb.AppendLine("{");

        // Application_Error body
        if (handlerBodies.TryGetValue("Application_Error", out var errorBody))
        {
            sb.AppendLine("    // Migrated from Application_Error — review and adapt:");
            foreach (var line in errorBody.Split('\n').Select(l => l.TrimEnd()))
            {
                if (!string.IsNullOrWhiteSpace(line))
                    sb.AppendLine($"    // {line}");
            }
            notes.Add("Application_Error body preserved as comments inside exception handler.");
        }

        sb.AppendLine("    app.UseExceptionHandler(\"/Home/Error\");");
        sb.AppendLine("    app.UseHsts();");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("app.UseHttpsRedirection();");
        sb.AppendLine("app.UseStaticFiles();");
        sb.AppendLine("app.UseRouting();");
        sb.AppendLine("app.UseAuthorization();");
        sb.AppendLine();

        // Session middleware (after UseRouting, before MapControllers)
        if (presentHandlers.Contains("Session_Start"))
        {
            sb.AppendLine("// app.UseSession(); // TODO: uncomment after adding AddSession() above");
            sb.AppendLine();
        }

        // Application_BeginRequest / EndRequest → middleware stub
        if (presentHandlers.Contains("Application_BeginRequest")
            || presentHandlers.Contains("Application_EndRequest"))
        {
            sb.AppendLine("// TODO: Migrate Application_BeginRequest/EndRequest to middleware:");
            sb.AppendLine("// app.Use(async (context, next) =>");
            sb.AppendLine("// {");
            sb.AppendLine("//     // BeginRequest logic here");
            sb.AppendLine("//     await next();");
            sb.AppendLine("//     // EndRequest logic here");
            sb.AppendLine("// });");
            sb.AppendLine();
            notes.Add("Application_BeginRequest/EndRequest → middleware stub added as comment.");
        }

        // Application_End → lifetime hook
        if (presentHandlers.Contains("Application_End"))
        {
            sb.AppendLine("// TODO: Application_End logic → register via IHostApplicationLifetime:");
            sb.AppendLine("// var lifetime = app.Services.GetRequiredService<IHostApplicationLifetime>();");
            sb.AppendLine("// lifetime.ApplicationStopped.Register(() => { /* your logic here */ });");
            sb.AppendLine();
            notes.Add("Application_End detected. Register cleanup via IHostApplicationLifetime.ApplicationStopped.");
        }

        sb.AppendLine("app.MapControllerRoute(");
        sb.AppendLine("    name: \"default\",");
        sb.AppendLine("    pattern: \"{controller=Home}/{action=Index}/{id?}\");");
        sb.AppendLine();
        sb.AppendLine("app.Run();");

        var content = sb.ToString();

        Directory.CreateDirectory(outputDirectory);
        var outputPath = Path.Combine(outputDirectory, "Program.cs");
        File.WriteAllText(outputPath, content, Encoding.UTF8);

        notes.Add($"Program.cs scaffold written to: {outputPath}");
        return new ConversionResult(outputPath, content, notes);
    }
}
